### ISSUE TITLE
Anyone having issues with the latest version 4.1.0?

### ISSUE THREAD

**Issue by jmbarroso** [Netflix/dgs-framework#377] opened 2021-06-01 17:50 UTC
Hi all, 

I found myself battling with my DGS project this morning; as there was no clear error log and my latest code changes didn't seem big enough to cause the issue, I decided to revert to the previous stable version of DGS. Problems were "solved" after changing the version.  

I'm wondering if any other person is experiencing issues or if there is something else conflicting with the new version. 

All came back to "normal" changing the dependency **implementation("com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter** from `latest.release` to `4.0.1`

Some details:
- IntelliJ Idea started missing the DGS dependencies showing **_Unresolved reference: Netflix_**
- Before rolling back the DGS version, I tried reloading/refreshing the Gradle config. It didn't fix the issue
- When running the DGS project and hitting the /graphql endpoint, got this error:
<img width="732" alt="Screen Shot 2021-06-01 at 10 38 34 AM" src="https://user-images.githubusercontent.com/1290289/120367795-2a10f680-c2c6-11eb-9188-45d06899bac9.png">

**Comment by paulbakker** [comment] 2021-06-07 17:20
@jmbarroso The `/graphql` path is the where you send the actual Graphql queries, and only supports POST. I think you were looking for `/graphiql` instead?

**Comment by jmbarroso** [comment] 2021-06-07 17:21
Yes, that was a typo when asking the question. I'm sorry!

**Comment by paulbakker** [comment] 2021-06-07 17:44
@jmbarroso I can't reproduce the issue, but my guess is that it's some dependency misalignment issue.
Can you use the BOM/platform dependency and try?

E.g.:

```
implementation(platform("com.netflix.graphql.dgs:graphql-dgs-platform-dependencies:4.1.0"))
implementation("com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter")
```

Docs about the BOM are [here](https://netflix.github.io/dgs/advanced/platform-bom/). I'll also update the getting-started guide, because this should really be there.

**Comment by jmbarroso** [comment] 2021-06-08 14:42
I will try the mentioned change this afternoon and share back. Thanks!

**Comment by paulbakker** [comment] 2021-06-08 18:04
I'm closing this, assuming there is no issue. If that turns out to be wrong, feel free to re-open.

**Closed by paulbakker** 2021-06-08 18:04 UTC
