### ISSUE TITLE
bug: GraphiQL not loading the schema 

### ISSUE THREAD

**Issue by mittalmridul** [Netflix/dgs-framework#770] opened 2021-12-06 13:24 UTC
## Expected behavior

Should load the schema and suggest autocomplete 
## Actual behavior
Showing Error when i try to open http://localhost:8080/graphiql .(It was working fine till 3rd December 2021)
Note: I am using this https://github.com/Netflix/dgs-examples-java project .
I havent made any changes to the project at all 

<img width="1428" alt="Screenshot 2021-12-06 at 6 22 05 PM" src="https://user-images.githubusercontent.com/29060403/144853213-179dd0ee-a8fb-4d07-96a1-2f122aa0167d.png">
<img width="1510" alt="Screenshot 2021-12-06 at 6 45 50 PM" src="https://user-images.githubusercontent.com/29060403/144853255-9d3dc8e1-d590-4357-a10b-dcebea7470aa.png">

## Steps to reproduce
create any new project and try opening http://localhost:8080/graphiql

_Note: A test case would be highly appreciated, but we understand that's not always possible_ 

NOTE : 1)I have tried several other projects as well and all of them are giving the same error . 
2) Although If i pass the correct query , I am getting the desired output

**Comment by nielsutrecht** [comment] 2021-12-06 14:43
Just ran into this too. It seems to be caused by a GraphiQL update: https://github.com/graphql/graphiql/issues/2085 that is incompatible with GraphQL < 16. 

I think the 'fix' on the DGS side is to not link to the 'latest' GraphiQL scripts but pin them to a version. It seems the author of GraphiQL just overwrites the 'production' scripts on a new release.

**Comment by mittalmridul** [comment] 2021-12-06 15:23
> Just ran into this too. It seems to be caused by a GraphiQL update: [graphql/graphiql#2085](https://github.com/graphql/graphiql/issues/2085) that is incompatible with GraphQL < 16.
> 
> I think the 'fix' on the DGS side is to not link to the 'latest' GraphiQL scripts but pin them to a version. It seems the author of GraphiQL just overwrites the 'production' scripts on a new release.

Oh ..good to know that I am not the only one facing this issue.. I had a demo today and this thing failed right in between the demo and i was really shocked and depressed with this failure in front of a lot of audience .

**Comment by nielsutrecht** [comment] 2021-12-06 15:37
It appears that they just fixed it by replacing the 'production' version.

Still, I think a good solution for DGS would be to pin the version used instead of pointing to the 'latest' version.

**Comment by srinivasankavitha** [comment] 2021-12-06 18:22
Thanks @mittalmridul  and @nielsutrecht for reporting the issue. Apologies @mittalmridul for the demo unexpectedly failing for you. We will fix this asap.

**Comment by srinivasankavitha** [comment] 2021-12-06 21:53
This will be available in the next release, closing this issue.

**Closed by srinivasankavitha** 2021-12-06 21:53 UTC
Labels: bug
