### ISSUE TITLE
feature: typeMapping support for ExtendedScalars.Json

### ISSUE THREAD

**Issue by sbilello** [Netflix/dgs-framework#215] opened 2021-03-30 00:31 UTC
Hello!

I was trying to add a`typeMapping` relying on the [JsonScalar](https://github.com/graphql-java/graphql-java-extended-scalars/blob/master/src/main/java/graphql/scalars/object/JsonScalar.java) from [graphql-java-extended-scalars](https://github.com/graphql-java/graphql-java-extended-scalars) 
it looks like that there is some visibility problem to make it work even if I added the dependency as `compile 'com.graphql-java:graphql-java-extended-scalars:16.0.0'`

It works fine if the class belongs to the same project repository and it is not an external dependency

```
generateJava{
    schemaPaths = ["${projectDir}/src/main/resources/schema"] // List of directories containing schema files
    packageName = 'com.example.demo' // The package name to use to generate sources
    generateClient = true // Enable generating the type safe query API
    typeMapping = ["JSON" : "graphql.Internal.JsonScalar"]
}
```

**Comment by paulbakker** [comment] 2021-03-30 17:02
It's probably related to this: https://github.com/graphql-java/graphql-java-extended-scalars/issues/38. The extended type libraries isn't published correctly it looks like.

I'm closing this issue as it doesn't seem to be actionable for us; please re-open is that turns out to be incorrect.

**Closed by paulbakker** 2021-03-30 17:02 UTC
Labels: enhancement

**Comment by sbilello** [comment] 2021-03-30 17:21
I fixed the dependency problem by adding `jcenter()` under `repositories` in `build.gradle` The dependency is there. @paulbakker

**Comment by paulbakker** [comment] 2021-04-01 00:16
> I fixed the dependency problem by adding `jcenter()` under `repositories` in `build.gradle` This is not a missing dependency problem @paulbakker. I can not re-open the issue because I am not a collaborator in this repository.

The issue I linked to mentions that. The issue is that it shouldn't be published just to jcenter, it should be in Maven central.
Since you fixed it by adding the repo manually (which would be a temporary workaround), there isn't an issue with the framework/codegen right?
