### ISSUE TITLE
bug: SnakeYaml android classfied jar is not found 

### ISSUE THREAD

**Issue by hantsy** [Netflix/dgs-framework#400] opened 2021-06-13 05:00 UTC
Latest DSG platform, when using Gradle as build tools, an error has occurred when building the application.

```
Could not find snakeyaml-1.28-android.jar (org.yaml:snakeyaml:1.28).
```

I have to exclude snakeyaml to overcome this issue. 

https://github.com/hantsy/spring-graphql-sample/blob/master/dgs-codegen/build.gradle

But the maven project does not report this issue.

https://github.com/hantsy/spring-graphql-sample/blob/master/dgs

## Expected behavior

```gradle
implementation "com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter"
```
## Actual behavior

```gradle
implementation "com.netflix.graphql.dgs:graphql-dgs-spring-boot-starter", {
      exclude group: 'org.yaml', module: 'snakeyaml'
}
```

**Comment by berngp** [comment] 2021-06-15 01:57
We have both a Java and Kotlin examples that run on every single pr as part of our build pipeline. I also see the dependency you mentioned available.  This was probably a transient issue resolving the artifact.

- https://github.com/Netflix/dgs-examples-java
- https://github.com/Netflix/dgs-examples-kotlin

**Comment by hantsy** [comment] 2021-06-15 02:16
When building the project, it only occurred in my Gradle project, not happened in the Maven project. 
I am not sure what happened in the Gradle dependency resolving.

**Comment by paulbakker** [comment] 2021-08-13 19:03
Closing because haven't seen this issue and can't reproduce it.

**Closed** 2021-08-13 19:03 UTC
Labels: bug, invalid

**Comment by hantsy** [comment] 2021-08-15 03:27
@paulbakker  Check my `gradlew build --scan` result of the **dgs-framework** on my **Windows**, check the result here: https://scans.gradle.com/s/vb3kn46n5whgk

And this error only occurred under Windows/Gradle. 

I also tried to [create some Maven projects](https://github.com/hantsy/spring-graphql-sample/tree/master/dgs), they did not repot this error.

**Comment by hantsy** [comment] 2021-08-15 04:42
@paulbakker  I have to add [this change](https://github.com/Netflix/dgs-framework/blob/c37ffcca0bb4f4c11909f27ba4d7afb2eb73e117/graphql-dgs-mocking/build.gradle.kts#L19-L21)  in the Gradle build script of dgs-mocking module to make sure it is built successfully under Windows.


```kotlin
    implementation("com.github.javafaker:javafaker:1.+") {
        exclude("org.yaml", "snakeyaml")
    }
```

**Comment by hantsy** [comment] 2021-08-15 04:50
Not sure how Gradle resolved the duplicated deps. `com.github.javafaker:javafaker` depends on a lower version of  `snakeyaml` but it aligned the version with the higher version of  `snakeyaml` that declared in the spring-boot-dependencies. But I am not sure why it used an **android** variant.

In Maven, when resolving the dependencies  of a project, it will ignore the lower version in the dependencies tree, and choose the higher version directly.
