### ISSUE TITLE
bug: upgrading to 4.6.0/4.7.3 leads to DgsInvalidInputArgumentException

### ISSUE THREAD

**Issue by EugenMayer** [Netflix/dgs-framework#584] opened 2021-08-29 09:45 UTC
We have this query

```
    spaces(
       first: Int!, 
		offset: Int!
        search: String,
        type: SpaceTypeFilter = BASIC,
        sortBy: [SpaceSortBy] = [{direction: ASC, field: TITLE}, {direction: ASC, field: ID}]
    ): SpaceGraphQlViewConnection!

input UserSortBy {
    field: UserSortByField,
    direction: SortDirection = ASC
}

enum UserSortByField {
    ID,
    USER_NAME,
    FIRST_NAME,
    LAST_NAME,
    COMPANY,
    EMAIL
}

enum SortDirection {
    ASC,
    DESC
}
```

While this works just find with 4.5.1, we get an exception in 4.6.0/4.7.0

```
com.netflix.graphql.dgs.exceptions.DgsInvalidInputArgumentException: Specified type 'class de.kontextwork.dwcore.base.space.model.api.SpaceSortBy' is invalid for sortBy.
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.processInputArgument(DataFetcherInvoker.kt:198) ~[graphql-dgs-4.6.0.jar:4.6.0]
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.invokeDataFetcher(DataFetcherInvoker.kt:62) ~[graphql-dgs-4.6.0.jar:4.6.0]
	at com.netflix.graphql.dgs.internal.DgsSchemaProvider.createBasicDataFetcher$lambda-19(DgsSchemaProvider.kt:310) ~[graphql-dgs-4.6.0.jar:4.6.0]
	at com.netflix.graphql.dgs.internal.DgsSchemaProvider$$Lambda$1209/0x0000000000000000.get(Unknown Source) ~[?:?]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270) [graphql-java-16.2.jar:?]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203) [graphql-java-16.2.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60) [graphql-java-16.2.jar:?]
	at graphql.execution.Execution.executeOperation(Execution.java:165) [graphql-java-16.2.jar:?]
	at graphql.execution.Execution.execute(Execution.java:104) [graphql-java-16.2.jar:?]
	at graphql.GraphQL.execute(GraphQL.java:557) [graphql-java-16.2.jar:?]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:482) [graphql-java-16.2.jar:?]
	at graphql.GraphQL.executeAsync(GraphQL.java:446) [graphql-java-16.2.jar:?]
	at com.netflix.graphql.dgs.internal.BaseDgsQueryExecutor.baseExecute(DefaultDgsQueryExecutor.kt:226) [graphql-dgs-4.6.0.jar:4.6.0]
	at com.netflix.graphql.dgs.internal.DefaultDgsQueryExecutor.execute(DefaultDgsQueryExecutor.kt:80) [graphql-dgs-4.6.0.jar:4.6.0]
	at com.netflix.graphql.dgs.internal.DefaultDgsQueryExecutor.getJsonResult(DefaultDgsQueryExecutor.kt:156) [graphql-dgs-4.6.0.jar:4.6.0]
	at com.netflix.graphql.dgs.internal.DefaultDgsQueryExecutor.getJsonResult$default(DefaultDgsQueryExecutor.kt:155) [graphql-dgs-4.6.0.jar:4.6.0]
	at com.netflix.graphql.dgs.internal.DefaultDgsQueryExecutor.executeAndExtractJsonPath(DefaultDgsQueryExecutor.kt:106) [graphql-dgs-4.6.0.jar:4.6.0]
	at com.netflix.graphql.dgs.DgsQueryExecutor.executeAndExtractJsonPath(DgsQueryExecutor.java:103) [graphql-dgs-4.6.0.jar:4.6.0]
	at de.kontextwork.dwcore.base.space.graphql.SpaceDataFetcherFullTest.getSpaces(SpaceDataFetcherFullTest.java:102) [test/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688) [junit-platform-commons-1.7.2.jar:1.7.2]
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$151/0x0000000000000000.apply(Unknown Source) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall$$Lambda$152/0x0000000000000000.apply(Unknown Source) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker$$Lambda$1533/0x0000000000000000.apply(Unknown Source) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor$$Lambda$1672/0x0000000000000000.execute(Unknown Source) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65) [junit-jupiter-engine-5.7.2.jar:5.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$230/0x0000000000000000.execute(Unknown Source) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$229/0x0000000000000000.invoke(Unknown Source) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$228/0x0000000000000000.execute(Unknown Source) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$234/0x0000000000000000.accept(Unknown Source) [junit-platform-engine-1.7.2.jar:1.7.2]
	at java.util.ArrayList.forEach(ArrayList.java:1541) [?:?]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$230/0x0000000000000000.execute(Unknown Source) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$229/0x0000000000000000.invoke(Unknown Source) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$228/0x0000000000000000.execute(Unknown Source) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$234/0x0000000000000000.accept(Unknown Source) [junit-platform-engine-1.7.2.jar:1.7.2]
	at java.util.ArrayList.forEach(ArrayList.java:1541) [?:?]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$230/0x0000000000000000.execute(Unknown Source) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$229/0x0000000000000000.invoke(Unknown Source) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$228/0x0000000000000000.execute(Unknown Source) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51) [junit-platform-engine-1.7.2.jar:1.7.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108) [junit-platform-launcher-1.7.2.jar:1.7.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88) [junit-platform-launcher-1.7.2.jar:1.7.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54) [junit-platform-launcher-1.7.2.jar:1.7.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator$$Lambda$183/0x0000000000000000.accept(Unknown Source) [junit-platform-launcher-1.7.2.jar:1.7.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67) [junit-platform-launcher-1.7.2.jar:1.7.2]
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52) [junit-platform-launcher-1.7.2.jar:1.7.2]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96) [junit-platform-launcher-1.7.2.jar:1.7.2]
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75) [junit-platform-launcher-1.7.2.jar:1.7.2]
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71) [junit5-rt.jar:?]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:221) [junit-rt.jar:?]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54) [junit-rt.jar:?]
Caused by: java.lang.NoSuchFieldException: field
	at java.lang.Class.getDeclaredFieldImpl(Native Method) ~[?:?]
	at java.lang.Class.getDeclaredFieldInternal(Class.java:910) ~[?:?]
	at java.lang.Class.getDeclaredField(Class.java:885) ~[?:?]
	at com.netflix.graphql.dgs.internal.InputObjectMapper.mapToJavaObject(InputObjectMapper.kt:55) ~[graphql-dgs-4.6.0.jar:4.6.0]
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.convertValue(DataFetcherInvoker.kt:238) ~[graphql-dgs-4.6.0.jar:4.6.0]
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.processInputArgument(DataFetcherInvoker.kt:196) ~[graphql-dgs-4.6.0.jar:4.6.0]

```

Not sure I can understand what changed in this regard by the Changelogs - did we do something wrong in the first place?

Thanks

**Comment by berngp** [comment] 2021-08-30 17:59
@EugenMayer any chance you are serializing to an array without specifying the collection type? 
If so could you please  try using `@InputArgument(collectionType = SpaceSortBy.class)` to confirm that works correctly?


Ref.  https://github.com/Netflix/dgs-framework/issues/588#issuecomment-908553322

**Comment by paulbakker** [comment] 2021-08-30 20:21
Closing this as invalid, based on the test I've added (see comment above). Please re-open if that turns out to be incorrect.

**Comment by berngp** [comment] 2021-08-31 01:36
Issue #591

**Comment by EugenMayer** [comment] 2021-09-01 14:26
Sorry for reporting so late. Not sure how this issue turned out.
First it was a 'invalid' and now #591 fixes bugs in this regard, which is release with 4.7.0?

Anyway, neither 4.6.0/4.7.0 does work for me. For to the questions:

Yes it is typed (and was typed) or it would not work in 4.5.1 either.

```java
@InputArgument(collectionType = SpaceSortBy.class) List<SpaceSortBy> sortBy
```

```Java
@EqualsAndHashCode(callSuper = true)
@Data
@AllArgsConstructor
public class SpaceSortBy extends SortBy<SpaceSortByField>
{
}
```

```java
/**
 * Common sort-by-tuple to define which field and in which order a entity should be sorted.
 *
 * @param <F> The sort by field enum like {@link SpaceSortByField}
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class SortBy<F extends Enum<F>>
{
  private F field;
  private SortDirection direction;

  public static String fieldToFieldName(Enum<?> field)
  {
    return CaseFormat.UPPER_UNDERSCORE.to(CaseFormat.LOWER_CAMEL, field.name());
  }
}
```

In graphql definition

```graphqls
spaces(
    first: Int!, offset: Int!
    search: String,
    type: SpaceTypeFilter = BASIC,
    sortBy: [SpaceSortBy] = [{direction: ASC, field: TITLE}, {direction: ASC, field: ID}]
): SpaceGraphQlViewConnection!

"Space fields to sort by"
enum SpaceSortByField {
    ID,
    TITLE
}

"Sort order defintion for a space"
input SpaceSortBy {
    field: SpaceSortByField,
    direction: SortDirection = ASC
}

enum SortDirection {
    ASC,
    DESC
}
```
I would pledge to reopen this one, I do not thing this is sovled yet.

**Comment by EugenMayer** [comment] 2021-09-02 05:53
I have seen that 4.7.2 has been released on github with a fix and test for this issue https://github.com/Netflix/dgs-framework/pull/595.

Is there a reason it is not referencing this issue in some sort, maybe I miss something (the test case seems to be the exact scenario here).

Anyway, 4.7.2 seems to yet not been publish to the nexus somehow https://mvnrepository.com/artifact/com.netflix.graphql.dgs/graphql-dgs-platform-dependencies - maybe you are yet unaware (or it was by intention idnk).

Thank you for working on this one

**Comment by paulbakker** [comment] 2021-09-02 15:35
Sorry about the confusion. We ran into an Artifactory issue yesterday, so we couldn't publish the release. It's there now (`7.0.3`). It doesn't fix your issue though.

I did [add a test](https://github.com/Netflix/dgs-framework/blob/master/graphql-dgs/src/test/kotlin/com/netflix/graphql/dgs/internal/InputArgumentTest.kt#L1629) based on your example (the one you found), but couldn't reproduce the issue. The test passed (before making some additional changes), so it's still a mystery what the issue is. If you could help provide a test for the issue (or a project that reproduces it) that would be very helpful since I'm running out of ideas on what to test. If you see what's missing in the test I added, feel free to modify that one.

`7.0.3` does fix one other issue which is specific to handling the `Object / JSON` scalar that triggered a corner case in the conversion, but I have no reason to believe that that's fixing your issue.

**Comment by EugenMayer** [comment] 2021-09-03 07:02
@paulbakker thank you for explaining and giving insight. It was indeed a bit confusing for me, but well maybe it is just a beast issue :)

Just checked your test. I would say that the `graphqls` part is identical - it should really reproduce it.

The only thing that could be different is the java (kotlin) implementation of the generic. You do not use any generics AFACIS and that might be the difference when type scanning

So the implementation of the base class here 

```
/**
 * Common sort-by-tuple to define which field and in which order a entity should be sorted.
 *
 * @param <F> The sort by field enum like {@link SpaceSortByField}
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class SortBy<F extends Enum<F>>
{
  private F field;
  private SortDirection direction;

  public static String fieldToFieldName(Enum<?> field)
  {
    return CaseFormat.UPPER_UNDERSCORE.to(CaseFormat.LOWER_CAMEL, field.name());
  }
}
```

Should make the difference (I assume). Sinc anything else is basically 1:1. What do you think?

**Comment by EugenMayer** [comment] 2021-09-06 06:25
I went forward the other way arround and reduced the complexity and removed the generic for now on our side, which leads to something else which maybe is equality interesting

```java
@Data
@AllArgsConstructor
public class SpaceSortBy
{
  private SpaceSortByField field;
  private SortDirection direction;

  public static String fieldToFieldName(Enum<SpaceSortByField> field)
  {
    return CaseFormat.UPPER_UNDERSCORE.to(CaseFormat.LOWER_CAMEL, field.name());
  }
}

public enum SortDirection
{
  ASC,
  DESC
}

public enum SpaceSortByField
{
  ID,
  TITLE,
}
```

with the exact same graphql definition as before

```graphqls
enum SortDirection {
    ASC,
    DESC
}

enum SpaceTypeFilter {
    BASIC,
    DESKTOP
}

"Space fields to sort by"
enum SpaceSortByField {
    ID,
    TITLE
}

"Sort order definition for a space"
input SpaceSortBy {
    field: SpaceSortByField,
    direction: SortDirection = ASC
}

spaces(
   offset: Int!
    search: String,
    type: SpaceTypeFilter = BASIC,
    sortBy: [SpaceSortBy] = [{direction: ASC, field: TITLE}, {direction: ASC, field: ID}]
): SpaceGraphQlViewConnection!
```

now leads to

```
com.netflix.graphql.dgs.exceptions.DgsInvalidInputArgumentException: Specified type 'class de.kontextwork.dwcore.base.space.model.api.SpaceSortBy' is invalid for sortBy.
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.processInputArgument(DataFetcherInvoker.kt:198) ~[graphql-dgs-4.7.0.jar:4.7.0]
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.invokeDataFetcher(DataFetcherInvoker.kt:62) ~[graphql-dgs-4.7.0.jar:4.7.0]
	at com.netflix.graphql.dgs.internal.DgsSchemaProvider.createBasicDataFetcher$lambda-19(DgsSchemaProvider.kt:310) ~[graphql-dgs-4.7.0.jar:4.7.0]
	at com.netflix.graphql.dgs.internal.DgsSchemaProvider$$Lambda$1209/0x0000000000000000.get(Unknown Source) ~[?:?]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270) [graphql-java-16.2.jar:?]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203) [graphql-java-16.2.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60) [graphql-java-16.2.jar:?]
	at graphql.execution.Execution.executeOperation(Execution.java:165) [graphql-java-16.2.jar:?]
	at graphql.execution.Execution.execute(Execution.java:104) [graphql-java-16.2.jar:?]
```

which is not what I would have expected with this change at all.

Digging in, I found out that the missing no args constructor on what the issue

```
@Data
@AllArgsConstructor
@NoArgsConstructor
public class SpaceSortBy {}
```

So with the generic removed ,things work out when the type has a no-args constructor (which is surely common, but we might consider a better error like in hibernate for the same cause?).

So going back to the generic implementation, the noargs constructor was already there, since the parent class had private fields and we use all-args-constructor on the child (without fields present) - which made me wander if that is the issue (reflection wise, the private fields which we actually rely on as a contract)

so I used 

```java
public class SortBy<F extends Enum<F>>
{
  protected F field;
  protected SortDirection direction;

  public static String fieldToFieldName(Enum<?> field)
  {
    return CaseFormat.UPPER_UNDERSCORE.to(CaseFormat.LOWER_CAMEL, field.name());
  }
}

@EqualsAndHashCode(callSuper = true)
@Data
@NoArgsConstructor
public class SpaceSortBy extends SortBy<SpaceSortByField>
{
}
```

But got an 

```
com.netflix.graphql.dgs.exceptions.DgsInvalidInputArgumentException: Specified type 'class de.kontextwork.dwcore.base.space.model.api.SpaceSortBy' is invalid for sortBy.
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.processInputArgument(DataFetcherInvoker.kt:198) ~[graphql-dgs-4.7.0.jar:4.7.0]
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.invokeDataFetcher(DataFetcherInvoker.kt:62) ~[graphql-dgs-4.7.0.jar:4.7.0]
	at com.netflix.graphql.dgs.internal.DgsSchemaProvider.createBasicDataFetcher$lambda-19(DgsSchemaProvider.kt:310) ~[graphql-dgs-4.7.0.jar:4.7.0]
	at com.netflix.graphql.dgs.internal.DgsSchemaProvider$$Lambda$1209/0x0000000000000000.get(Unknown Source) ~[?:?]
```

so nothing really changed. Still we somehow now it is ether an issue with inheritance or the generic.

So to reduce it further, I ruled out generics as the cause by changing it 

```java
@EqualsAndHashCode(callSuper = true)
@Data
@NoArgsConstructor
public class SpaceSortBy extends SortBy
{
}

public class SortBy
{
  protected SpaceSortByField field;
  protected SortDirection direction;

  public static String fieldToFieldName(Enum<?> field)
  {
    return CaseFormat.UPPER_UNDERSCORE.to(CaseFormat.LOWER_CAMEL, field.name());
  }
}
```

which still leads to 

```
com.netflix.graphql.dgs.exceptions.DgsInvalidInputArgumentException: Specified type 'class de.kontextwork.dwcore.base.space.model.api.SpaceSortBy' is invalid for sortBy.
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.processInputArgument(DataFetcherInvoker.kt:198) ~[graphql-dgs-4.7.0.jar:4.7.0]
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.invokeDataFetcher(DataFetcherInvoker.kt:62) ~[graphql-dgs-4.7.0.jar:4.7.0]
	at com.netflix.graphql.dgs.internal.DgsSchemaProvider.createBasicDataFetcher$lambda-19(DgsSchemaProvider.kt:310) ~[graphql-dgs-4.7.0.jar:4.7.0]
```

So for you to reproduce it, you need the inheritance present, the simple one without any generic.

The working example for me (and that is why it is working for you) is 

```java
@Data
@AllArgsConstructor
@NoArgsConstructor
// FIXME: use base class and remove inline implementation
//  as soon as we get https://github.com/Netflix/dgs-framework/issues/584 fixed
//@EqualsAndHashCode(callSuper = true)
public class SpaceSortBy //  extends SortBy<SpaceSortByField>
{
  private SpaceSortByField field;
  private SortDirection direction;

  public static String fieldToFieldName(Enum<?> field)
  {
    return CaseFormat.UPPER_UNDERSCORE.to(CaseFormat.LOWER_CAMEL, field.name());
  }
}
```

I hope this helps to circle in on the problem!

**Comment by carmas-RatedPower** [comment] 2021-09-07 14:21
Hi, I can confirm that this same issue is happening to me. As @EugenMayer pointed out, seems to be related with inheritance when specifying the InputArgument collectionType with a concrete type.

As of version 4.6.0 (graphql-dgs-platform BOM) this issue seemed to be arising. Find attached below a very simple test case to reproduce this issue.

Hope this helps to spot the bug. Kind regards.

[test-case.zip](https://github.com/Netflix/dgs-framework/files/7122192/test-case.zip)

**Comment by paulbakker** [comment] 2021-09-08 00:04
There were two issues at play:
1) Subclasses - this was an easy fix
2) Generics - this was not an easy fix, because of generics in Java...

It all seems to work now. We added a number of tests for scenarios with generics.
Thanks again for pointing out the issue.

The changes will be released tomorrow.

**Closed by paulbakker** 2021-09-08 00:04 UTC
Labels: bug

**Comment by EugenMayer** [comment] 2021-09-09 07:21
I hat to bring this up, but it did not work for me @paulbakker 

```
com.netflix.graphql.dgs.exceptions.DgsInvalidInputArgumentException: Specified type 'class de.kontextwork.dwcore.base.space.model.api.SpaceSortBy' is invalid for sortBy.
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.processInputArgument(DataFetcherInvoker.kt:198) ~[graphql-dgs-4.7.4.jar:4.7.4]
	at com.netflix.graphql.dgs.internal.DataFetcherInvoker.invokeDataFetcher(DataFetcherInvoker.kt:62) ~[graphql-dgs-4.7.4.jar:4.7.4]
	at com.netflix.graphql.dgs.internal.DgsSchemaProvider.createBasicDataFetcher$lambda-19(DgsSchemaProvider.kt:310) ~[graphql-dgs-4.7.4.jar:4.7.4]
	at com.netflix.graphql.dgs.internal.DgsSchemaProvider$$Lambda$1209/0x0000000000000000.get(Unknown Source) ~[?:?]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270) [graphql-java-16.2.jar:?]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203) [graphql-java-16.2.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60) [graphql-java-16.2.jar:?]
```

Did you test thee generics?

I use
 
```java
@Data
@AllArgsConstructor
public class SpaceSortBy extends SortBy<SpaceSortByField>
{
}

@Data
@AllArgsConstructor
@NoArgsConstructor
public class SortBy<F extends Enum<F>>
{
  private F field;
  private SortDirection direction;

  public static String fieldToFieldName(Enum<?> field)
  {
    return CaseFormat.UPPER_UNDERSCORE.to(CaseFormat.LOWER_CAMEL, field.name());
  }
}
```

**Comment by paulbakker** [comment] 2021-09-09 18:39
The release took a little longer because we found another (unrelated) issue. It's out now: https://github.com/Netflix/dgs-framework/releases/tag/v4.7.5

**Comment by EugenMayer** [comment] 2021-09-10 06:31
@paulbakker seems like https://github.com/Netflix/dgs-framework/releases/tag/v4.7.6 has generic-fixes too. But 4.7.5 and 4.7.6 are both missing as boms https://mvnrepository.com/artifact/com.netflix.graphql.dgs/graphql-dgs-platform-dependencies

It always takes a day or two for the to get published, right?

**Comment by EugenMayer** [comment] 2021-09-13 05:58
Great, i finally can confirm that 4.7.6 (and maybe 4.7.5) is fixing this issue for both, inheritance and generics.

Thank you for all the effort!

**Comment by carmas-RatedPower** [comment] 2021-09-16 14:40
I've been able to test 4.7.6 and the issue is resolved.

Thank you all for being so proactive and keep up the good work with this awesome framework!
