### ISSUE TITLE
bug: Invalid syntax will throw 500 error.

### ISSUE THREAD

**Issue by caojiaqi123** [Netflix/dgs-framework#1499] opened 2023-04-27 10:19 UTC
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.
Invalid syntax with throw 500 error.
## Expected behavior
{
    "errors": [
        {
            "message": "Invalid syntax with XXXX at line 5 column 2",
            "locations": [
                {
                    "line": 5,
                    "column": 2
                }
            ],
            "extensions": {
                "classification": "InvalidSyntax"
            }
        }
    ]
}
## Actual behavior
{
  "timestamp": 1682590475829,
  "status": 500,
  "error": "Internal Server Error",
  "path": "/graphql"
}
## Steps to reproduce
test in post man, below is a correct schema, then remove one   '}' 
{
    testDatafetcher{
        id
    }
}

_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by srinivasankavitha** [comment] 2023-05-11 23:45
I do see the expected behavior when testing with graphiql and with postman against the latest master/release. Please ensure you are on the latest code. Closing this issue for now since I cannot reproduce the error.

**Closed by srinivasankavitha** 2023-05-11 23:45 UTC
Labels: bug
