### ISSUE TITLE
Unsafe TypedGraphQLError constants (INTERNAL, NOT_FOUND...)

### ISSUE THREAD

**Issue by kiov** [Netflix/dgs-framework#130] opened 2021-03-08 15:54 UTC
`TypedGraphQLError` has some statics fields like `INTERNAL`, `NOT_FOUND`, an so on.

The problem is that they reuse the same builder instance:

```java
    public static Builder INTERNAL = newBuilder().errorType(ErrorType.INTERNAL);
```
`Builder` instances are not thread safe and could share state between threads.

Multiples threads could be using the same unsafe instance.

Test code:
```java
final Semaphore s1 = new Semaphore(0);
final Semaphore s2 = new Semaphore(0);

ForkJoinTask<TypedGraphQLError> t1 = ForkJoinPool.commonPool().submit(() -> {
  Builder t = TypedGraphQLError.INTERNAL.extensions(Map.of("t", "1"));
  // allows t2 to run
  s2.release();

  //wait for t2
  s1.acquire();
  return t.build();
});
ForkJoinTask<TypedGraphQLError> t2 = ForkJoinPool.commonPool().submit(() -> {
  // ensures that t1 runs first
  s2.acquire();
  Builder t = TypedGraphQLError.INTERNAL.extensions(Map.of("t", "2"));
  // allows to t1 to return
  s1.release();
  return t.build();
});
TypedGraphQLError thread1Result = t1.join();
TypedGraphQLError thread2Result = t2.join();

if (thread1Result.getExtensions().get("t").equals("1")) {
  System.out.println("Thread 1: OK");
} else {
  System.out.println("Thread 1: Race condition, should be 1 instead of " + thread1Result.getExtensions().get("t"));
}

if (thread2Result.getExtensions().get("t").equals("2")) {
  System.out.println("Thread 2: OK");
} else {
  System.out.println("Thread 2: Race condition, should be 2 instead of " + thread2Result.getExtensions().get("t"));
}
```
Prints:
```
Thread 1: Race condition, should be 1 instead of 2
Thread 2: OK
```

Also this effectively allows to remap error as other types:
```java
TypedGraphQLError internalError = TypedGraphQLError.INTERNAL.build();
if (internalError.getExtensions().get("errorType").equals("INTERNAL")) {
  System.out.println("OK: INTERNAL error is INTERNAL");
} else {
  System.out.println("ERROR: INTERNAL error is " + internalError.getExtensions().get("errorType"));
}
// remap internal error as BAD_REQUEST
TypedGraphQLError.INTERNAL.errorType(ErrorType.BAD_REQUEST).build();

TypedGraphQLError remapedInternalError = TypedGraphQLError.INTERNAL.build();
if (remapedInternalError.getExtensions().get("errorType").equals("INTERNAL")) {
  System.out.println("OK: INTERNAL error is INTERNAL");
} else {
  System.out.println("ERROR: INTERNAL error is " + remapedInternalError.getExtensions().get("errorType"));
}
``` 
Prints
```
OK: INTERNAL error is INTERNAL
ERROR: INTERNAL error is BAD_REQUEST
```

**Comment by paulbakker** [comment] 2021-03-08 17:55
Good find! That should definitely get fixed.

**Comment by paulbakker** [comment] 2021-03-17 21:12
Note that I'm looking at this - but not quite sure yet what to do about it. The problem is obvious, but I don't (yet) see how to fix it without also breaking the API that a lot of folks depend on already :-(

**Comment by paulbakker** [comment] 2021-03-23 00:28
The only real fix for this issue is to remove the static field. An alternative is already available in the form of just invoking `newBuilder()`. 
In the PR I deprecated the static fields, so we can remove them in a future major release and to discourage usage.

**Closed** 2021-03-23 17:03 UTC
Labels: bug
