### ISSUE TITLE
Cannot pass null parameter to the query

### ISSUE THREAD

**Issue by vilkazz** [Netflix/dgs-framework#280] opened 2021-04-18 12:08 UTC
## Expected behavior
When passing a nullable parameter, i.e. `filterString`, I'd expect to be able to pass it as null when building the query (this works in the gql-java-kickstart). This framework, however, crashes with a NPE: `environment.getArgument(parameterNames[idx]) must not be null`. 

There is a workaround to not pass the parameter at all, however that beats the purpose of having nullable parameters~

Update: 
Naming a parameter as shown below also solves this issue.
works:
```
@DgsQuery
public List<Movie> movies(@InputArgument(name = "filter") String filter, int size, int page {..}
```
crashes:
```
@DgsQuery
public List<Movie> movies(String filter, int size, int page {..}
```

Since the naming workaround is possible, my issue is technically solved, however I want to leave the actual issue here for triaging on whether the nameless approach is a bug or intended behavior.

## Actual behavior
Query crashes with the following error
> java.lang.NullPointerException: environment.getArgument(parameterNames[idx]) must not be null
	at com.netflix.graphql.dgs.internal.DgsSchemaProvider.invokeDataFetcher(DgsSchemaProvider.kt:386) ~[graphql-dgs-3.11.0.jar:3.11.0]
	at com.netflix.graphql.dgs.internal.DgsSchemaProvider.access$invokeDataFetcher(DgsSchemaProvider.kt:64) ~[graphql-dgs-3.11.0.jar:3.11.0]
	at com.netflix.graphql.dgs.internal.DgsSchemaProvider$createBasicDataFetcher$1.get(DgsSchemaProvider.kt:279) ~[graphql-dgs-3.11.0.jar:3.11.0]
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:270) ~[graphql-java-16.2.jar:na]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:203) ~[graphql-java-16.2.jar:na]

## Steps to reproduce
Any query with a null parameter, against a null-allowed query i.e.

```
movies(filter: String size: Int = 5 page: Int = 0): [Movie]
```

```
{
	"operationName":"getMovies",
	"variables":{"filterString":null,"page":0,"size":20},
	"query":"query getMovies( 
		$filterString: String, 
		$page: Int, 
		$size: Int
	) 
	{
		movies(
			$filterString: String, 
			$page: Int!, 
			$size: Int!
		) {
			id
			name
			rating
		}	
	}
}
```

**Comment by berngp** [comment] 2021-04-18 17:00
Thanks for reporting it.

**Comment by srinivasankavitha** [comment] 2021-04-22 22:42
@vilkazz - I am not able to reproduce this problem. Do you have a branch that I can try out? Also please check that you are using the latest release `v3.11.0`

**Comment by vilkazz** [comment] 2021-04-23 05:24
Hi @srinivasankavitha, I have created a repo with the repro of the issue. Please find it here: https://github.com/vilkazz/dgs-null-param-test. 

I have put my repro steps in readme of the said project~

**Comment by srinivasankavitha** [comment] 2021-04-23 17:58
Thanks for posting your code. For your resolver in `badQuery`, you actually need either use @InputArgument, or you need to actually extract the fields from the dfe within your resolver. You currently are trying the one below and it is missing `@InputArgument` annotation altogether, which won't work.
```
  @DgsQuery
  public boolean badQuery(
      String filter,
      int size,
      int page,
      String sort
  ) {
    return true;
  }
}
```

With the framework, the resolver for `badQuery` you need to do either one as shown below.

```
Use @InputArgument like so:
@DgsQuery
public boolean badQuery(
            @InputArgument String filter,
            @InputArgument int size,
            @InputArgument int page,
            @InputArgument String sort
) {
        return true;
}
```
or directly extract from DFE:
```
@DgsQuery
public boolean badQuery(DgsDataFetchingEnvironment dfe) {
        String filter = dfe.getArgument("filter");
        return true;
}
```

**Comment by srinivasankavitha** [comment] 2021-04-23 17:59
Closing this issue as we don't support the requested syntax in the framework.

**Closed by srinivasankavitha** 2021-04-23 17:59 UTC
Labels: bug

**Comment by vilkazz** [comment] 2021-04-24 02:31
Thanks for the explanation! 

I thought this to be the case, was just slightly put off by the NPE thrown by the framework when the badQuery was used~
