### ISSUE TITLE
bug: Custom Scalars are not parsed when included in `_entities` query representations

### ISSUE THREAD

**Issue by gwardwell** [Netflix/dgs-framework#1569] opened 2023-06-29 04:43 UTC
Unlike field arguments which parse custom scalar values on the way into a data fetcher, custom scalars are not parsed when included in `_entities` query representations.

#### Schema

```graphql
# Parses to `Long`
scalar Int64

type Book @key(fields: "bookId") {
  bookId: Int64!
}

type Query {
  bookById(bookId: Int64!): Book
}
```

#### Query

Query:

```graphql
query GetEntities($representations: [_Any!]!) {
  _entities(representations: $representations) {
    ... on Book {
      __typename
      bookId
    }
  }
}
```

Variables:

```json
{
  "representations": [
    {
      "__typename": "Book",
      "bookId": "7654323234565432345676543234567"
    }
  ]
}
```

#### Data Fetchers

```java
@DgsQuery
public CompletableFuture<DemoBook> book(
    // `bookId` is parsed to a `Long` by the custom scalar logic
    @InputArgument(value = "bookId") Long bookId
) {
  ...
}

@DgsEntityFetcher(name = "Book")
public CompletableFuture<Book> book(Map<String, Object> values) {
  // The `bookId` is not parsed to a `Long` by the custom scalar and is
  // instead typed as a generic `Object`, but is actually a String.
  String bookId = (String) values.get("bookId");
  ...
}
```

### Nested Keys

Nested keys may provide complication in solving this problem as only the root level of an entity representation includes the `__typename`. But all fields in the key are represented in the schema, making the schema a "source of truth" for mapping these nested types.

#### Schema

```graphql
# Parses to `Long`
scalar Int64

# Parses to `OffsetDateTime`
scalar DateTime

type Book @key(fields: "bookId publicationInfo { publicationDate }") {
  bookId: Int64!
  publicationInfo: PublicationInfo!
}

type PublicationInfo {
  publicationDate: DateTime!
}

type Query {
  bookById(bookId: Int64!): Book
}
```

#### Query

Query:

```graphql
query GetEntities($representations: [_Any!]!) {
  _entities(representations: $representations) {
    ... on Book {
      __typename
      bookId
      publicationInfo {
        publicationDate
      }
    }
  }
}
```

Variables:

```json
{
  "representations": [
    {
      "__typename": "Book",
      "bookId": "7654323234565432345676543234567",
      "publicationInfo": {
        "publicationDate": "2020-02-08 09:30:26"
      }
    }
  ]
}
```

## Expected behavior

Generated DGS code would provide proper typing and scalar parsing for entity representations in entity data fetchers based on the shape of the schema.

## Actual behavior

Entity representations must be manually transformed, which is error prone and contrary to behavior of the custom scalars elsewhere in data fetcher implementations.

```java
@DgsEntityFetcher(name = "Book")
public CompletableFuture<Book> book(BookRepresentation book) {
  Long bookId = book.getBookId();
  ...
}
```

## Steps to reproduce

1. Create a federated subgraph service with DGS
2. Create a custom scalar the parses a value into a concrete type (like an `Int64` custom scalar that serializes to a string and parses to a `Long`)
3. Create a GraphQL Entity that uses the custom scalar for a field return type, using the field that returns the custom scalar as one of the entity keys
4. Create a `@DgsEntityFetcher` for the entity
5. Perform an `_entities` query and observe that the key field using the custom scalar is not parsed

**Comment by gwardwell** [comment] 2023-06-29 13:56
A few more thoughts.

If DGS can take an entity representation like this:

```json
{
  "representations": [
    {
      "__typename": "Book",
      "bookId": "7654323234565432345676543234567"
    }
  ]
}
```

And understand the representation enough to route it to the Entity Fetcher, then it should be able to apply the representation JSON to a class that hardens up the shape of the data. Using something like Jackson, it could be done as long as there was a class to apply the JSON to:

```java
new ObjectMapper().readValue(json, SomeEntityClass.class)
```

It would require codegen for those representation classes (unless the entity class itself could be used) and it would need to ensure that custom scalar parsing was applied to the right fields in the class.

**Comment by srinivasankavitha** [comment] 2023-06-29 22:59
Thanks for the detailed explanation of the issue. We will look into a fix for this in an upcoming release. The issue is clearly related to the fact that we are not handling special coercing when custom scalars are used as keys. The framework does handle entity fetchers a bit differently than regular data fetchers and is therefore missing this functionality.

**Comment by sutarias** [comment] 2023-07-21 16:57
Hi I am running into a similar issue with my entity query/dataFetcher where I am trying to pass in an integer but the DataFetcher is reading it as a generic `Object` and a (BigInteger) instead of Integer. 

I was wondering the status on this fix, if someone was already working on it or if assistance from external contributors would be helpful?

**Comment by srinivasankavitha** [comment] 2023-07-21 17:52
We haven't started looking at it, so if you are able to make a
contribution, we welcome it!

**Comment by wbaldoumas** [comment] 2023-09-15 15:39
> The issue is clearly related to the fact that we are not handling special coercing when custom scalars are used as keys. The framework does handle entity fetchers a bit differently than regular data fetchers and is therefore missing this functionality.

@srinivasankavitha for external folks looking to contribute to a fix here but are unfamiliar with the repository setup, could you point to where this is currently handled and where the fix might need to be applied?

**Comment by wbaldoumas** [comment] 2023-10-15 01:54
I chatted with @berngp about a possible implementation to alleviate this issue and tried my hand at it. It should allow DGS users to encapsulate parsing logic for any kind of entity representations, including representations with nested types and custom scalars. 

Feel free to take a look [here](https://github.com/Netflix/dgs-framework/pull/1669) and let me know what you think. 😄

**Comment by srinivasankavitha** [comment] 2023-10-16 22:21
Thanks for the PR @wbaldoumas. I will take a look shortly and share thoughts.

**Closed** 2023-11-17 18:02 UTC
Labels: bug
