### ISSUE TITLE
bug: @RequestHeader inject the null value for all header

### ISSUE THREAD

**Issue by umesh-kushwaha** [Netflix/dgs-framework#185] opened 2021-03-23 15:09 UTC
Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md) before
creating an issue.

## Expected behavior
`public String hello(@RequestHeader String host) `

host should not be null.
## Actual behavior
host is always null.
## Steps to reproduce
`public String hello(@RequestHeader String host) `

send the header and print the log to check the host value. 
_Note: A test case would be highly appreciated, but we understand that's not always possible_

**Comment by paulbakker** [comment] 2021-03-23 16:47
I can't reproduce this - all tests and examples seem to work. Can you provide a test case?

One thing to try is to use an explicit name: `@RequestHeader("host") String host)`. Depending on your compiler settings the argument name might not be available.

Closing the issue until more details provided.

**Closed by paulbakker** 2021-03-23 16:47 UTC
Labels: bug
